### ISSUE TITLE
Shesheta not merging approved PR

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/support#1]
This PR has been approved for +16 hours, but Shesheta as not merged it. help! :fearful:  

https://github.com/aicoe-aiops/ocp-ci-analysis/pull/289#issuecomment-872545802

**Comment by pacospace** [comment]
> This PR has been approved for +16 hours, but Shesheta as not merged it. help! 
> 
> [aicoe-aiops/ocp-ci-analysis#289 (comment)](https://github.com/aicoe-aiops/ocp-ci-analysis/pull/289#issuecomment-872545802)

Thanks @MichaelClifford for opening this issue, it should prow tide in charge of merging, but for some reason prow is a bit slow. We will investigate on this cc @harshad16 @goern @tumido

**Comment by goern** [comment]
Hmm if you click on the "tide details" link on the status section
![image](https://user-images.githubusercontent.com/260331/124303174-6902c800-db62-11eb-9bf6-355f4c909582.png)

and have a look at it https://prow.operate-first.cloud/pr?query=is%3Apr+repo%3Aaicoe-aiops%2Focp-ci-analysis+author%3Aamsaparov+head%3Amaster

it simply says "do-not-merge/hold"

**Comment by MichaelClifford** [comment]
:+1:
