### ISSUE TITLE
Kebechet is not able to release my version of the manage-dependencies-tutorial

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/support#109]
**Describe the bug**
Following the steps described in the [manage-dependencies-tutorial](https://github.com/AICoE/manage-dependencies-tutorial/blob/master/docs/thoth-aicoe-services.md#create-new-release), Kebechet did not automatically release my version and the bot label was not available for this issue on my branch.

**To Reproduce**
Follow the steps of the tutorial until the "Create a new release" section included.

**Expected behavior**
Kebechet automatically creates a new minor release.

**Comment by harshad16** [comment]
checking the deployment
