### ISSUE TITLE
Thoth refers to pyifd rather than pyIFD for thoth-station/ps-ip

### ISSUE THREAD

**Issue by EldritchJS** [thoth-station/support#114]
**Describe the bug**
pyIFD is considered pyifd by Thoth

**To Reproduce**
1. `git clone https://github.com/thoth-station/ps-ip`
2. run `thamos advise`
3. observe mention of `pyifd` rather than `pyIFD`

**Expected behavior**
I expect `pyIFD` to be mentioned rather than `pyifd`

**Screenshots**
```
https://thoth-station.n │ No versions were found  │ -            │ ❌ ERROR   
  inja/j/solve_direct     │ for direct dependency   │              │            
                          │ 'pyifd'; operating      │              │            
                          │ system 'rhel' in OS     │              │            
                          │ version '8' for Python  │              │            
                          │ in version '3.8' using  │              │            
                          │ platform 'linux-x86_64' │              │            
  https://thoth-station.n │ Resolver failed as it   │ pyifd        │ ❌ ERROR   
  inja/j/unresolved       │ was unable to resolve   │              │            
                          │ direct dependency       │              │            
                          │ 'pyifd'                 │              │            
                          ╵                         ╵              ╵            
                   Unable to resolve all direct dependencies                
```

**Additional context**

**Comment by EldritchJS** [comment]
Update: I modified Pipefile to use lowercase for pyifd, Pipefile.lock should be happy now. Still seeing the errors mentioned above, though I believe @pacospace said those are expected until Thoth knows what pyifd is!

**Comment by pacospace** [comment]
> Update: I modified Pipefile to use lowercase for pyifd, Pipefile.lock should be happy now. Still seeing the errors mentioned above, though I believe @pacospace said those are expected until Thoth knows what pyifd is!

I'm sorry @EldritchJS, I forgot one thing: Thoth does not learn from requests from `CLI`, but only from `Bots`, I triggered a `Kebechet Update` issue in ps-ip repo, so Kebechet should submit a request to Thoth with the Pipfile and start learning. Alternatvetly we need to manually trigger Thoth to learn that package. (I will do that as well in case)
