### ISSUE TITLE
Prow is requiring `/ok-to-test` on bot accounts even though `ok-to-test` label is already present

### ISSUE THREAD

**Issue by tumido** [thoth-station/support#122]
**Describe the bug**
We use dependabot to manage NPM package upgrades and dependencies. Dependabot doesn't have a real github user account that can be invited to the org. And prow requires all external contributions to be approved to be tested. I've configured dependabot to apply the `ok-to-test` label on PR creation but that doesn't help and prow still applies the `need-ok-to-test` label even when there's `ok-to-test` label present already.

**To Reproduce**
1. Install dependabot
2. Configure it so it applies `ok-to-test` label
3. Let it create PR
4. Let the PR be noticed by Prow
5. See that the PR now has both `ok-to-test` and `needs-ok-to-test` labels

**Expected behavior**
When `ok-to-test` is present the `needs-ok-to-test` is not applied and tests are run without Prow whining about it.

**Screenshots**
![image](https://user-images.githubusercontent.com/7453394/138072139-d0d31d49-2384-4dbb-b421-fff59e9dfca6.png)

**Additional context**
See this PR as an example:
https://github.com/AICoE/meteor/pull/185

And this dependabot config:
https://github.com/AICoE/meteor/blob/main/.github/dependabot.yml

**Comment by codificat** [comment]
As `ok-to-test` implies trust, do we want to have this automated to begin with?

Dependabot is not the only affected bot. Here is an example with sefkhet-abwy: https://github.com/thoth-station/report-processing/pull/145

There seem to be explicit hardcoded exceptions for our bots: https://github.com/AICoE/sefkhet-abwy/blob/1fa87f71c4fe01597fbbd8e553d0481b15db1561/aicoe/sesheta/review_manager.py#L168-L190

Just double checking here: do we want something similar for dependabot?

**Comment by tumido** [comment]
> As `ok-to-test` implies trust, do we want to have this automated to begin with?

@codificat Of course we do! Using any bots implies trust. So.. if user voluntarily opts-in to use a bot to maintain their dependency stack - like dependabot in this case and even configures it [to apply the `ok-to-test` label](https://github.com/AICoE/meteor/blob/2f2fc29b281e3aa8593212e1c0cb13f906f5f15e/.github/dependabot.yml#L12-L13) because he knows the bots purpose and wants the PRs validated by CI. If all of this is true, I don't think Prow should come and block it (by applying `neees-ok-to-test` label).

I see few problems here:
1. Prow doesn't allow us to say that we trust any github appication with PRs. Using the same narrative Prow automatically assumes we trust all organization members, because org members are automatically "ok-to-test" every time. If we have to always trust all the org members with running the CI on their PRs, I think we should have the option to say we trust a bot with the same. 
2. Prow is happy with PRs that comes with `ok-to-test` and still applies the `needs-ok-to-test` label. PRs with both labels should simply not be possible and if the PR already has the `ok-to-test` label when Prow is checking it, Prow should not be stubborn about applying the `needs-ok-to-test`.
3. If I opt in to use a bot to make PRs for me, I really don't want to come to all the PRs it creates and every time see that the CI was not executed, because Prow decided so. A review on a simple dependency bump PR is now turned from a minute task when everything is already laid out in front of me into a process when I need to permit the CI, wait for it and if it fails I'd need to come back to the PR... It costs time
4. From experience - I have `/ok-to-test`ed all the PRs created by dependabot. Every time. I think I can say I trust it with CI.
5. Bots should relieve us from doing chores, not create new chores. This is a chore for me.

> There seem to be explicit hardcoded exceptions for our bots: https://github.com/AICoE/sefkhet-abwy/blob/1fa87f71c4fe01597fbbd8e553d0481b15db1561/aicoe/sesheta/review_manager.py#L168-L190

I don't think this is related. The problem we're discussing here is that we've already applied the `ok-to-test` label on the PR. We should have already bypassed it. Yet Prow is still stubborn about it and adds the `needs-ok-to-test` and PR is then left with both of the labels meaning CI is not executed. Also we're not talking here about auto-approve, just ok-to-test.

> Just double checking here: do we want something similar for dependabot?

Ideally Prow should allow us to configure the "external users" that are not required to be OKed to test, similarly as it does with [branch protection](https://github.com/thoth-station/thoth-application/blob/7125af9438e0b54f5879ebaba3bcf9168ca68704/prow/overlays/smaug/config.yaml#L75)

**Comment by tumido** [comment]
/close

Resolved. As tested by https://github.com/operate-first/apps/pull/2611 `trusted_apps` work
