### ISSUE TITLE
CUDA enabled notebook images on quay.io/thoth-station

### ISSUE THREAD

**Issue by erikerlandson** [thoth-station/support#14]
**Is your feature request related to a problem? Please describe.**
As a thoth and aicoe-ci user, I would like one or two standard public builds of gpu-enabled notebooks

**High-level Goals**
- gpu enabled notebook image published in quay.io

**Describe the solution you'd like**
Add new repo for something like `s2i-ml-gpu-notebook` 

**Describe alternatives you've considered**
private image builds

**Additional context**
Per discussion with Steve Huels, the nvidia EULA allows CUDA libs to be built into images that are publicly available on quay.io (based on a discussion with nvidia's legal dept)

**Comment by goern** [comment]
with https://issues.redhat.com/projects/ODH/issues/ODH-417?filter=allopenissues I have started a discussion on this. As we can not publically provide NVIDIA based images, we need to build them locally, and restrict their distribution. The update you provided via Steve is new to me and needs some source reference.

**Comment by harshad16** [comment]
We would not be publishing CUDA images on thoth-station org in quay.
Maybe opendatahub provided CUDA images on opendatahub-io-contrib https://quay.io/repository/opendatahub-contrib/workbench-images?tab=tags can be helpful and more details are here https://github.com/opendatahub-io-contrib/workbench-images#cuda-base-images.
