### ISSUE TITLE
"Kebechet pipfile-requirements manager: FileNotFoundError

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/support#15]
I have received emails with the message "Kebechet pipfile-requirements manager: FileNotFoundError" for both [aicoe-aiops/ocp-ci-analysis](https://github.com/aicoe-aiops/ocp-ci-analysis) and [aicoe-aiops/github-labeler](https://github.com/aicoe-aiops/github-labeler). 

issues:

https://github.com/aicoe-aiops/ocp-ci-analysis/issues/345
https://github.com/aicoe-aiops/github-labeler/issues/35

I'm not sure where this error is coming from or what I need to do to address it. What is the pipefile-requirements manager? 

The Trace back in the email points twords an issue with
 `File "/home/user/kebechet/managers/pipfile_requirements/pipfile_requirements.py"`

**Comment by goern** [comment]
Cant we generate the file? Or is this a situation where we want to create a github issue? or send a PR to fix?

/assign @KPostOffice 
/priority important-soon

**Comment by fridex** [comment]
Then you can turn the manager off by removing it from the `managers` section. It can be useful only for cases when the repo keeps a project that is CLI and a library at the same time.

**Comment by MichaelClifford** [comment]
Cool, thanks for the Response @fridex. I'll go ahead and remove this from the template's `thoth.yaml` then as very few (if any) of our repo's follow this CLI and library structure.
