### ISSUE TITLE
Create pyIFD wheel and host on AI CoE Index

### ISSUE THREAD

**Issue by EldritchJS** [thoth-station/support#16]
**Is your feature request related to a problem? Please describe.**
As an image forensics scientist I would like a managed and stable pyIFD wheel available via the AI CoE index.

**High-level Goals**
Hosted pyIFD wheel.

**Describe the solution you'd like**
A hosted pyIFD wheel.

**Describe alternatives you've considered**
Forcing pyIFD user to build both JPEGIO and pyIFD locally via https://github.com/eldritchjs/pyIFD

**Additional context**
pyIFD relies on a fork of JPEGIO which currently is built locally as part of building/installing pyIFD.

**Acceptance Criteria**
1. pyIFD wheel hosted on AI CoE index

**Comment by goern** [comment]
/priority backlog
/assign @EldritchJS
/triage accepted

@EldritchJS @pacospace any updates on this?

**Comment by pacospace** [comment]
See @fridex comments: https://github.com/thoth-station/support/issues/17#issuecomment-908048959

**Comment by fridex** [comment]
The pulp instance is up and running. If you want to proceed with this one, [feel free to follow the docs](https://www.operate-first.cloud/community-handbook/pulp/usage.md). We would be happy to support index creation and hosting packages (I'm not sure about the index name here).

**Comment by goern** [comment]
@EldritchJS if this is something you want to implement, feel free to reopen the issue! 
/close
