### ISSUE TITLE
Kebechet GitHub Connection Error handling

### ISSUE THREAD

**Issue by goern** [thoth-station/support#168]
**Is your feature request related to a problem? Please describe.**
This is a meta-issue to shad some light on three questions:
1. is it safe to leave closed any issue referencing this issue here
2. should we turn the exception handling of any issue referencing this issue into metrics, so that we can raise an altert
3. shall we leave error handling via rasing exception as is?

/kind feature
/priority important-soon
/assign @KPostOffice

**Comment by codificat** [comment]
Note that https://github.com/thoth-station/support/issues/134#issuecomment-967142783 has a suggestion on a possible action

**Comment by codificat** [comment]
On a review today, this is believed to be fixed already

/close

**Comment by codificat** [comment]
The bot missed the previous comment, trying again:
/close
