### ISSUE TITLE
Create JPEGIO wheel and host on AI CoE Index

### ISSUE THREAD

**Issue by EldritchJS** [thoth-station/support#17]
**Is your feature request related to a problem? Please describe.**
As an image processing scientist I would like to have a reliable updated version of the JPEGIO library available.

**High-level Goals**
Modify forked JPEGIO to conform with AI CoE standard and host its wheel on AI CoE index. Current repo: https://github.com/eldritchjs/jpegio

**Describe the solution you'd like**
JPEGIO wheel hosted and available to all who wish to use it.

**Describe alternatives you've considered**
Forcing library user to build locally from GH repo.

**Additional context**

**Acceptance Criteria**
Wheel hosted on AI CoE.

**Comment by fridex** [comment]
Hi Jason,

thanks for reaching out. We are provisioning [a new solution for hosting Python indices](https://www.operate-first.cloud/users/pulp/usage.md) so this might take some time - hope that's fine and this is not time crucial. Is the wheel specific to AICoE organization or should we create a new Python index specific for these builds (also wheel mentioned in https://github.com/thoth-station/support/issues/16).

**Comment by codificat** [comment]
/remove-lifecycle stale
depends on https://github.com/operate-first/support/issues/176 (pulp availability)

**Comment by fridex** [comment]
See https://github.com/thoth-station/support/issues/16#issuecomment-1014713528

**Comment by goern** [comment]
@EldritchJS if this is something you want to implement, feel free to reopen the issue! 
/close
