### ISSUE TITLE
failed thamos advise links to 404 thoth-search result

### ISSUE THREAD

**Issue by goern** [thoth-station/support#179]
**Describe the bug**
When executing a `thamos advise` and it fails due to `Unable to resolve all direct dependencies`, the result still pointed to a thoth-search URL, which actually gives http/404

**To Reproduce**
1. `git clone ... kebechet`
2. `git checkout 15cc8bc88a2f3038b1f3ad9468ebd2873e3da829`
3. `thamos -v advise --no-dev`
4. see result

**Expected behaviour**

**Screenshots**

**Additional context**

/assign @Gkrumbach07 
/priority important-soon

**Comment by Gkrumbach07** [comment]
@goern What was the exact link that was given? Assuming no document_id is given, the link would most likely look like `https://thoth-station.ninja/search/advise/`. In that case the app is working correctly because there was no id provided. I could create a custom 404 page for these instances that will notify you the user that there was no id provided.

**Comment by Gkrumbach07** [comment]
When I ran thamos I was given the link https://thoth-station.ninja/search/advise/adviser-220119133853-3342a89ae14b8ca0/summary. This pointed to a non 404 search link. The app did fail eventually due to the 500 type api errors, but not 404. Is this also what you noticed or did you see a 404 page?

**Comment by Gkrumbach07** [comment]
After looking at the failed api calls, It seems like the versions in the pipfile.lock from the inputs were not known to Thoth. Because all were not known, then the app crashed. That looks like a bug on the UI side.

**Comment by fridex** [comment]
It might be that the issue was originally referring to an old link to Thoth Search UI in adviser output (when `thoth-search` was part of the URL). This was fixed with the release.

**Comment by Gkrumbach07** [comment]
In that case we can probably close this issue. I will open an issue to add some tests regrading different data coming in. This will be able to catch the problem case I described above.

**Comment by fridex** [comment]
Sounds reasonable. Thanks!

/close
