### ISSUE TITLE
Move pyIFD repository to AI CoE hosting

### ISSUE THREAD

**Issue by EldritchJS** [thoth-station/support#18]
**Is your feature request related to a problem? Please describe.**
As an AI CoE member I would like to see pyIFD hosted within the group hosting.

**High-level Goals**
https://github.com/eldritchjs/pyIFD hosted on AI CoE repo space.

**Describe the solution you'd like**
The current repository moved to AI CoE repo space, with hosted wheels per issues 16 and 17.

**Describe alternatives you've considered**
Hosting on authors' personal GH repository.

**Additional context**

**Acceptance Criteria**
1. https://github.com/eldritchjs/pyIFD hosted on AI CoE repo space.

**Comment by goern** [comment]
/priority backlog
/assign @EldritchJS 
/triage accepted

@EldritchJS @pacospace any updates on this?

**Comment by pacospace** [comment]
@EldritchJS can you please request one using https://github.com/AICoE/common/issues/new?assignees=tumido%2Cgoern&labels=kind%2Fquestion&template=repo-create.yaml&title=CREATE%3A+%3Crepo_name%3E?
