### ISSUE TITLE
Kebechet doesnt seems to function on the OS-climate repo

### ISSUE THREAD

**Issue by harshad16** [thoth-station/support#19]
**Describe the bug**
Kebechet was setup on the os-climate repo, however it doesn't seems to function on it.
https://github.com/os-climate/data-platform-demo/issues/3, 

cc: @erikerlandson

**Comment by erikerlandson** [comment]
not sure if it is related but I tried filing a direct `Deliver Container Image` build and that doesn't seem to be happening either:
https://github.com/os-climate/data-platform-demo/issues/4

(this mode worked a day or two ago)

**Comment by harshad16** [comment]
This issue seems to be due to the cluster down 
We need to check our backup cluster and test this out.

**Comment by harshad16** [comment]
Kebechet is functioning well:
https://github.com/os-climate/data-platform-demo/pull/38
closing this issue.
