### ISSUE TITLE
[2pt] setup Kebechet to maintain https://github.com/opendatahub-io/s2i-lab-elyra

### ISSUE THREAD

**Issue by goern** [thoth-station/support#194]
**Is your feature request related to a problem? Please describe.**
Elyra version outdated.

**Describe the solution you'd like**
Set up Kebechet to maintain https://github.com/opendatahub-io/s2i-lab-elyra dependencies shall be kept up to date based on Thoth Guidance Service (adivser-manager) and new container image version shall be delivered to quay.io

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Acceptance Criteria**

- [ ] Kebechet is opening PR to update Pipfile/.lock
- [ ] new releases created based on github issues
- [ ] new container image tags delivered based on releases

/priority critical-urgent
/assign @KPostOffice 
/cc @romeokienzler

**Comment by harshad16** [comment]
Installation of kebechet for s2i-lab-elyra is done.
![Screenshot from 2022-09-13 09-43-25](https://user-images.githubusercontent.com/14028058/189917686-1b5ca84c-1d2f-496e-b175-7e04a3ee69dc.png)

![Screenshot from 2022-09-13 09-43-25](https://user-images.githubusercontent.com/14028058/189917670-272962c7-1bc2-4c97-bb3c-3e3314ab29e5.png)

Closing the issue.
