### ISSUE TITLE
CI for https://github.com/thoth-station/solver-errors-reporter is broken

### ISSUE THREAD

**Issue by goern** [thoth-station/support#198]
**Describe the bug**
SSIA

**To Reproduce**
1. Go to one of the kebechet PR in https://github.com/thoth-station/solver-errors-reporter

**Expected behavior**
PR gets merged by cyborgs

looks like this is still on zuul, some major CI config files are missing

/priority important-soon
/assign @Gregory-Pereira

**Comment by goern** [comment]
@Gregory-Pereira did #38 solve this issue?

**Comment by Gregory-Pereira** [comment]
Not exactly sure, but I think so. I saw that #39 got merged and that it was automatically approved by Sesheta, but it shows Harshad as the person who merged it, and the `aicoe/build-check` status as pending. The build-check itself shouldn't have passed anyway, seeing as there is no `build` paramater in our `.aicoe-ci.yaml` file. The tekton pipeline-run cannot be found so I can't go back and check the logs. Ill confer with @harshad16, but in the meanwhile we may have to wait for another PR in this repo.

**Comment by Gregory-Pereira** [comment]
ping @harshad16

**Comment by goern** [comment]
Hmm, I think so.

@harshad16 wdyt?
/assign @harshad16

**Comment by harshad16** [comment]
yes we can close this.
closing.
