### ISSUE TITLE
container image mentioned contains outdated/wrong versions

### ISSUE THREAD

**Issue by goern** [thoth-station/support#204]
**Describe the bug**
In https://redhat-scholars.github.io/managing-vulnerabilities-with-thoth/managing-vulnerabilities-with-thoth/01-run-application.html there is mentioned to use a container to run thamos, that container image has only python3.9 and thamos 1.21.1

Same is true for the master tag of https://quay.io/repository/thoth-station/s2i-thoth-f34-py39?tab=tags&tag=latest

**To Reproduce**
1. Go to https://redhat-scholars.github.io/managing-vulnerabilities-with-thoth/managing-vulnerabilities-with-thoth/01-run-application.html
2. Execute `docker run --rm -it --entrypoint bash quay.io/thoth-station/s2i-thoth-f34-py39:v0.32.3 # or use podman` as mentioned 
3. Run `thamos version` in the container
4. Run `python --version` in the container
5. Run `python.38` in the container
6. See that py38 is required by `.thoth.yaml`

**Expected behavior**
The container image used has the latest version of thamos and a version of Python3.8

**Additional context**
n/a

/priority critical-urgent
/assign @mayaCostantini

**Comment by mayaCostantini** [comment]
Addressed by https://github.com/redhat-scholars/managing-vulnerabilities-with-thoth/pull/38 and https://github.com/thoth-station/s2i-thoth/pull/238
