### ISSUE TITLE
[1pt] aiographql-client needed ofr Sefkhet-Abwy

### ISSUE THREAD

**Issue by goern** [thoth-station/support#217]
### Package name

aiographql-client

### Reason

the package is required to resolve github.com/AICoE/sefkhet-abwy

**Acceptance criteria**
-  [x] schedule the solver for the package using the [management-api.](https://management.stage.thoth-station.ninja/api/v1/ui/#/Python%20Solver/post_solve_python)
-  [x] verify the package is ingested by project thoth using [user-api](https://stage.thoth-station.ninja/api/v1/ui/#/PythonPackages/list_python_package_versions).

**Comment by harshad16** [comment]
comments: https://chat.google.com/room/AAAAVjnVXFk/E2k4_L7_SMY

**Comment by mayaCostantini** [comment]
Closing this issue as the package is now available in Thoth's database.
