### ISSUE TITLE
the URL that points to an advise's results gives a 404

### ISSUE THREAD

**Issue by codificat** [thoth-station/support#219]
**Describe the bug**

When I ask for an advise, one of the *info* items I get is a URL to explore the results on the website.

However, accessing that URL results on an HTTP 404 (not found).

**To Reproduce**

1. Run `thamos advise`
2. Look at the results
3. Find a line like this:

|Link|Message|
|---|---|
| https://thoth-station.ninja/search/adviser-220520135456-693dce14c5adfe00/summary|Results can be browsed in Thoth search |
  
**Expected behavior**

The link should work

**Additional context**

The correct URL path seems to be `/search/advise/:id:` (i.e. add `/advise/`)

**Comment by Gkrumbach07** [comment]
That is a broken link. 

Link is missing the '/advise/'.

Working link is https://thoth-station.ninja/search/advise/adviser-220520135456-693dce14c5adfe00/summary

**Comment by codificat** [comment]
Sorry, I forgot to
/assign
myself.  Note that there is a PR to fix this already linked:  thoth-station/adviser#2341
/unassign @Gkrumbach07 
/lifecycle active
