### ISSUE TITLE
Provide a pre-commit hook for the Thoth adviser

### ISSUE THREAD

**Issue by TomasTomecek** [thoth-station/support#233]
**Is your feature request related to a problem? Please describe.**
I can run Thoth using [pre-commit](https://pre-commit.com/) both locally and in CI via the same workflow. GHA only provides the CI part.

**High-level Goals**
Teams can add Thoth pre-commit hook in their `.pre-commit-config.yaml`.

**Describe the solution you'd like**
Provide a [pre-commit hook](https://pre-commit.com/) that can run Thoth on GitHub PRs, and especially run it locally.

**Describe alternatives you've considered**
GHA is a solid alternative.

**Additional context**
∅

**Acceptance Criteria**
See goals above.

8 story points :P

**Comment by harshad16** [comment]
/triage accepted
/sig stack-guidance

thanks for the issue, we had some discussion regarding this
it's great to know users would like this.

**Comment by mayaCostantini** [comment]
@TomasTomecek a first release of the Thoth pre-commit hook is available at https://github.com/thoth-station/thoth-pre-commit-hook
Feedback and feature propositions are welcome!

**Comment by TomasTomecek** [comment]
wow, that's awesome, thank you! we have also prioritized recently the task to use thoth, will add the link to the pre-commit hook there

**Comment by erikerlandson** [comment]
that is great news!  :tada:

**Comment by erikerlandson** [comment]
@mayaCostantini  in the `thoth advise` usage statement I don't see what the options are for `--recommendation-type`

**Comment by mayaCostantini** [comment]
Let's close this issue as the pre-commit hook is now available at https://github.com/thoth-station/thoth-pre-commit-hook
