### ISSUE TITLE
Include Torchvision

### ISSUE THREAD

**Issue by guimou** [thoth-station/support#245]
### Package name

torchvision

### Python package index URL

https://pypi.org/project/torchvision/

### Reason

Torchvision is used a lot by people doing image recognition with PyTorch. It's even include in RHODS' Pytorch image, so it should be part of Thoth.

**Comment by harshad16** [comment]
Story pt: 2pt

**Comment by codificat** [comment]
This seems to be in the database now:

```
$ http 'https://khemenu.thoth-station.ninja/api/v1/python/package/versions?name=torchvision' | jq -r '.versions[].package_version' | wc -l
107
```

so I believe this is complete and therefore going to
/close

If there's anything missing / wrong please reopen or create a new issue as appropriate.
