### ISSUE TITLE
Thoth natively supports a differential analysis

### ISSUE THREAD

**Issue by TomasTomecek** [thoth-station/support#257]
**Is your feature request related to a problem? Please describe.**

As a Thoth user, I'd love to compare an advise of a PR with an advise done on the main branch easily with a single `thamos advise` command.

**High-level Goals**

Running `advise` produces results that only contain difference from a different advise.
These are available both via Web UI and on CLI.

**Describe the solution you'd like**
That's up to you :)

**Additional context**
There already is a compare button in the Web UI. Sadly the past advises are not tagged in any way so it's hard to tell what to compare against.

**Acceptance Criteria**
* Running `thamos advise` produces results with difference from another analysis.

**Comment by harshad16** [comment]
This is regarding having similar compare support in thamos.
**Acceptance criteria**
- [ ]  Add additional command for compare of different advise analysis
- [ ] Utilize the function of the git diff.
- [ ]  Figure the way to store the advise id (small term cache) for comparision. 
- [ ]  Verify the result w.r.t to the search/compare. 


Story Point: [Epic][13pt]

**Comment by Gkrumbach07** [comment]
**Acceptance Criteria Issues** (covers points from https://github.com/thoth-station/support/issues/257#issuecomment-1194030035)

- [ ] https://github.com/thoth-station/thamos/issues/1147
- [ ] https://github.com/thoth-station/thamos/issues/1146

**Comment by goern** [comment]
/close
as we work on it on <see last comment>
