### ISSUE TITLE
[3pt] base notebook image do not build (or get published)

### ISSUE THREAD

**Issue by goern** [thoth-station/support#271]
**Describe the bug**
https://github.com/thoth-station/s2i-minimal-notebook/releases/tag/v0.4.0 has been released, but https://quay.io/repository/thoth-station/s2i-minimal-notebook?tab=tags is not having that tag.

**To Reproduce**
1. Go to https://quay.io/repository/thoth-station/s2i-minimal-notebook?tab=tags
2. Go to https://github.com/thoth-station/s2i-minimal-notebook/releases/tag/v0.4.0
3. compare tags

**Expected behavior**
tags are in sync

**Screenshots**
n/a

**Additional context**
n/a

**Comment by VannTen** [comment]
should be fixed by https://github.com/thoth-station/s2i-minimal-notebook/pull/567 + a new release

**Comment by VannTen** [comment]
There is now a v1.0.0 tag with the corresponding image. Does it fix this or is the missing image (v0.4.0) problematic ? @goern

**Comment by harshad16** [comment]
closing this issue.
It was fixed with: https://github.com/thoth-station/s2i-minimal-notebook/pull/567
