### ISSUE TITLE
Cannot find s2i-lab-elyra custom notebook source

### ISSUE THREAD

**Issue by pacospace** [thoth-station/support#3]
**Describe the bug**
Cannot find source of the image: https://quay.io/repository/thoth-station/s2i-elyra-custom-notebook?tab=info

**To Reproduce**

**Expected behavior**
Repo for tracking build of this image.

**Screenshots**

**Additional context**

**Comment by goern** [comment]
Even https://github.com/thoth-station/support/search?q=s2i-elyra-custom-notebook doesnt yield a good result

/triage accepted
/kind question

**Comment by harshad16** [comment]
let me take this , will provide the source soon
