### ISSUE TITLE
Use Sesheta Access Token for building operate-first.github.io

### ISSUE THREAD

**Issue by oindrillac** [thoth-station/support#68]
We need a Github token for the https://github.com/operate-first/operate-first.github.io repo which needs to be added under `Environment Variables` [Travis CI](https://app.travis-ci.com/github/operate-first/operate-first.github.io/settings) for automated website re-builds. Can we use Sesheta to provide a token for the same?

cc: @HumairAK @harshad16

**Comment by harshad16** [comment]
/triage accepted
Discussion is going on : https://operatefirst.slack.com/archives/C01RMPVUUK1/p1631732900111900

**Comment by HumairAK** [comment]
created a separate operate-first account for specifically operate-first org, this can be closed

**Comment by harshad16** [comment]
Thanks, closing this issue.
