### ISSUE TITLE
More documentation for the template issues for tag releases and redelivering containers. 

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/support#91]
**Is your feature request related to a problem? Please describe.**

Not sure if this issue should be tracked here or in https://github.com/aicoe-aiops/project-template. However, the template issues that are included in each of our projects through the template repo that are designed to interact with Thoth's build pipelines need more documentation to clarify use, expectations and differentiation between them. Specifically, major-release.md, minor-release.md, patch-release.md and redeliver_contianer_image.md. For user's unfamiliar with Thoth, there is no indication of how these issues will aid the user in delivering content images.   

**High-level Goals**
Additional instructions and explanation within each issue template explaining to users which build pipeline will be kicked off by opening the issue and how to track its progress.

**Comment by pacospace** [comment]
> Sure @pacospace Looks like @erikerlandson already started the discussion here: [thoth-station/core#316](https://github.com/thoth-station/core/issues/316) Shall we continue it there?

Sounds good!
