### ISSUE TITLE
Kebechet is not responding to ps-ip new patch release issue.

### ISSUE THREAD

**Issue by EldritchJS** [thoth-station/support#95]
**Describe the bug**
Kebechet is not responding to new patch release issue.

**To Reproduce**
1. Go to https://github.com/thoth-station/ps-ip
2. Click on Pull Requests
3. Scroll down 
4. See no PR from Kebechet

**Expected behavior**
My understanding is Kebechet is to create a PR as a next step after my patch release issue is created

**Screenshots**

**Additional context**

**Comment by harshad16** [comment]
Kebechet is now able to open the PR: https://github.com/thoth-station/ps-ip/pull/7

The reason, why it didn't work before:
we had an imagepullerror across the cluster, we had fixed the issue just a few hours before.
That was the cause for the previous request to be completed.
kebechet is on service now.
please let us know if there are any more issues.

Please close if the solution seems to be effective.

**Comment by EldritchJS** [comment]
Thanks @harshad16 !
